### Necessário para pegar o token
### Post
# @name loginAutenticado
POST http://localhost:40000/Login HTTP/1.1
content-type: application/json

{    
    "UserName": "admin",
    "Password": "admin"
}

### Seta o token
@accessToken = {{loginAutenticado.response.body.token}}


### Teste de buscar todas as agências
GET http://localhost:40000/getAllAgencia HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
}

### Teste de buscar uma agência pelo ID
POST http://localhost:40000/getAgenciaByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "agenciaid": 1
}

### Teste de inserção de nova agência
POST http://localhost:40000/insertAgencia HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "nome": "Agência Teste",
    "endereco": "Rua Teste, 123",
    "telefone": "123456789",
    "email": "agencia@teste.com",
    "data_criacao": "2021-01-01",
    "orcamento": 100000.50
}

### Teste de atualização de agência
POST http://localhost:40000/updateAgencia HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "agenciaid": 6,
    "nome": "Agência Atualizada",
    "endereco": "Rua Atualizada, 456",
    "telefone": "987654321",
    "email": "agencia@atualizada.com",
    "data_criacao": "2018-05-25",
    "orcamento": 156000.50
}

### Teste de deletar agência
POST http://localhost:40000/DeleteAgencia HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "agenciaid": 6 
}
